image: java:8-jdk

before_script:
  - export
  
stages:
  - build
  - package
  - deploy
  
gradle-build:
  image: gradle:alpine
  stage: build
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export VERSION = $(gradlew properties -q | grep \"version:\" | awk '{print \$2}')
    - export jarFile = $CI_PROJECT_NAME-$VERSION.jar

  script:
    - echo jarFile
    