image: java:8-jdk

before_script:
  - export
  
stages:
  - build
  - package
  - deploy
  
gradle-build:
  image: gradle:alpine
  stage: build
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export VERSION = $(grep -E "version " app/build.gradle | cut -d "\"" -f2)
    - export jarFile = $CI_PROJECT_NAME-$VERSION.jar
    - echo jarFile
    