image: java:8-jdk

before_script:
  - export
  
stages:
  - build
  - package
  - deploy
  
gradle-build:
  image: gradle:alpine
  stage: build
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    
    
  script:
    - gradle build

  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle/wrapper
  artifacts:
    paths:
      - build/libs/*.jar
  after_script:    

    - mv build/libs/demo-0.0.1-SNAPSHOT.jar build/libs/app.jar

image: docker:latest
services:
  - docker:18.09-dind
variables:
  DOCKER_HOST: tcp://docker:2375
        
docker-build:
  stage: package
  script:
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker image build -t app .
    - docker image tag app localhost:5000/app
    #- sudo docker image push localhost:5000/app
    
deploy-staging:
  stage: deploy
  script:
    #- ID=$(docker ps -a --filter="name=dev-$CI_PROJECT_NAME" -q) && [[ -n $ID ]] && docker stop $ID && docker rm $ID
    - docker rmi -f localhost:5000/app
    - docker container ls -a -f name=app -q | xargs -r docker container stop
    - docker container ls -a -f name=app -q | xargs -r docker container rm
    - docker run --name=app -d -p 9091:9091 app .
    #- docker run -d --name app --restart always --publish 9091:9091 
  environment:
    name: staging
    url: http://101.101.165.137:9091
  when: manual
  only:
    - master
    